"""empty message

Revision ID: 64126e191206
Revises: b933ecc400dd
Create Date: 2020-01-14 00:24:28.939172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64126e191206'
down_revision = 'b933ecc400dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('create_date', sa.DATETIME(), nullable=False))
    op.drop_column('registro', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.drop_column('registro', 'create_date')
    # ### end Alembic commands ###
