"""empty message

Revision ID: cb7c1abc2072
Revises: 64126e191206
Create Date: 2020-01-15 23:58:11.370839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7c1abc2072'
down_revision = '64126e191206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro', sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_registro_ID'), 'registro', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_ID'), table_name='registro')
    op.drop_column('registro', 'ID')
    # ### end Alembic commands ###
