"""empty message

Revision ID: f4585e832e60
Revises: 5bf622f2bc41
Create Date: 2019-12-26 22:42:47.811945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4585e832e60'
down_revision = '5bf622f2bc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_ID'), 'user', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ID'), table_name='user')
    # ### end Alembic commands ###
